services:
  redis_DB:
    image: redis
    container_name: redis_DB
    # network_mode: host
    networks:
      - redis_network
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:${REDIS_ABSOLUTE_PATH}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  tg_bot:
    build:
      context: ./
      dockerfile: Dockerfile.py
      # network: host
    image: nescafebot
    container_name: tg_bot
    # network_mode: host
    networks:
      - redis_network
    ports:
      - "79:8888"
    command: bash
    tty: true
    stdin_open: true

networks:
  redis_network:
    driver: bridge
