services:
  mongo_DB:
    container_name: mongo_DB
    image: mongo:7.0
    network_mode: host
    # networks:
      # - DB_network
    # ports:
      # - 27017:27017
    volumes:
      - ${MONGODB_ABSOLUTE_PATH}:/data/db 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  tg_bot:
    build:
      context: ./
      dockerfile: Dockerfile.py
      network: host
    image: nescafebot
    container_name: tg_bot
    network_mode: host
    # networks:
      # - DB_network
    # ports:
      # - 79:8888
    command: bash
    tty: true
    stdin_open: true

# networks:
  # DB_network:
    # driver: bridge

volumes:
  mongodata:
    driver: local
