version: '3.8'

services:
  redis_DB:
    image: redis
    container_name: redis_DB
    networks:
      - redis_network
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/c/Users/madfu/Documents/big_projects/redis.conf  # Mount the redis.conf file
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # Use the password from the .env file
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  tg_bot:
    image: nescafebot
    container_name: tg_bot
    networks:
      - redis_network
    ports:
      - "79:8888"

networks:
  redis_network:
    driver: bridge