version: '3.8'

services:
  redis_DB:
    image: redis
    container_name: redis_DB
    networks:
      - DB_network
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:${REDIS_ABSOLUTE_PATH}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  mongo_DB:
    container_name: mongo_DB
    image: mongo:7.0
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - DB_network
    volumes:
      - ${REDIS_ABSOLUTE_PATH}:/data/db

  tg_bot:
    build:
      context: ./
      dockerfile: Dockerfile.py
    image: nescafebot
    container_name: tg_bot
    networks:
      - DB_network
    ports:
      - 79:8888
    command: bash
    tty: true
    stdin_open: true

networks:
  DB_network:
    driver: bridge

volumes:
  mongodata:
    driver: local
